### ISSUE TITLE
Unable to install master

### ISSUE THREAD

**Issue by mattjegan** [uptick/pymyob#52]
I have tried to install from the last commit and it appears that pip doesn't know it needs to install requests-oauthlib. 

I ran `pip install git+https://github.com/uptick/pymyob.git@44b8c35444b73d6b35a7b79a9d60c4dd4ef7dd51#egg=pymyob`

Here is my stacktrace:

```

Collecting pymyob
  Cloning https://github.com/uptick/pymyob.git (to revision 44b8c35444b73d6b35a7b79a9d60c4dd4ef7dd51) to /private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob
  Running command git clone -q https://github.com/uptick/pymyob.git /private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob
    ERROR: Command errored out with exit status 1:
     command: /Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob/setup.py'"'"'; __file__='"'"'/private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob/pip-egg-info
         cwd: /private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob/
    Complete output (39 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob/setup.py", line 3, in <module>
        setup()
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/Users/eganm/.pyenv/versions/3.6.8/lib/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/_virtualenv.py", line 21, in parse_config_files
        result = old_parse_config_files(self, *args, **kwargs)
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/setuptools/dist.py", line 690, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/Users/eganm/.local/share/virtualenvs/xyzproject-xqRGoeqW/lib/python3.6/site-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/Users/eganm/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob/myob/__init__.py", line 1, in <module>
        from .api import Myob  # noqa
      File "/private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob/myob/api.py", line 1, in <module>
        from .credentials import PartnerCredentials
      File "/private/var/folders/75/8gmml8cd6rd5dswqq4sp4dr80000gn/T/pip-install-z8c919qt/pymyob/myob/credentials.py", line 4, in <module>
        from requests_oauthlib import OAuth2Session
    ModuleNotFoundError: No module named 'requests_oauthlib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jarekwg** [comment]
Hmm, so installing from egg ignores requirements?
Interesting.. If it used to work for you, then it could be related to https://github.com/uptick/pymyob/releases/tag/1.2.5

I don't have the time to investigate why it does this currently, but happy to accept a PR that addresses this. I'd like to move it all once more to pyproject.toml at some point, which may or may not magically address this issue.

Out of curiousity, why are you installing from eggs when the latest version is published on pypi?

**Comment by mattjegan** [comment]
Hi Jarek,

Thanks for the response. We install from egg because we install directly
from git as we have a fork of this repo. We noticed the issue after a
recent merge from trunk.

**Comment by jarekwg** [comment]
Ah, does manually installing `request-oauthlib==1.3.0` beforehand fix it for you in the interim?

**Comment by mattjegan** [comment]
@jarekwg I have just tested it and yes, if I `pip install requests-oauthlib==1.3.0` prior to installing pymyob it installs fine

**Comment by jarekwg** [comment]
Ok thanks, I guess you can use that as a bandaid soln until this issue is fixed then.
